extends:
  - eslint:recommended
  - plugin:node/recommended
  - plugin:jest/recommended
env:
  node: true
  mocha: true
  jest/globals: true
plugins:
  - import
  - jest
rules:
  no-console: 0
  # Sometimes I like a single 'return' statement in a full bloc, e.g. see the
  # tests, so relax the requirement to have single return statements
  arrow-body-style: 0
  import/no-extraneous-dependencies: [error, { devDependencies: ['**/*.test.js'] }]
  no-process-exit: 0
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
